export const TIMELINE_INIT = 'TIMELINE_INIT';
export const TIMELINE_CHANGE_PARTITION = 'TIMELINE_CHANGE_PARTITION';

export const TIMELINE_ERA_ENTERED = 'TIMELINE_ERA_ENTERED';
export const TIMELINE_ERA_PLUS = 'TIMELINE_ERA_PLUS';
export const TIMELINE_ERA_MINUS = 'TIMELINE_ERA_MINUS';
export const TIMELINE_ERA_ZOOM_IN = 'TIMELINE_ERA_ZOOM_IN';
export const TIMELINE_ERA_ZOOM_OUT = 'TIMELINE_ERA_ZOOM_OUT';
